INSERT INTO diplomski_radovi (id, naziv_rada, tekst_rada, link_rada, oib_tvrtke)
VALUES('25', 'Tema diplomskog rada: Utjecaj kvalitete napona na uređaje zaštite u distributivnim mrežama 10 kV', 'Utjecaj kvalitete napona na uređaje zaštite u distributivnim mrežama 10 kV', 'https://stup.ferit.hr/2018/01/31/tema-diplomskog-rada-utjecaj-kvalitete-napona-na-uredaje-zastite-u-distributivnim-mrezama-10-kv/', '9549425995201');
INSERT INTO diplomski_radovi (id, naziv_rada, tekst_rada, link_rada, oib_tvrtke)
VALUES('27', '3.	Projektiranje sustava dojave požara &#8211; zakonski, ekonomski i tehnički aspekti', 'Zadatak rada je analizirati važnost sustava dojave požara, zakonsku regulativu, ekonomski aspekt ugradnje sustava te na primjeru iz prakse dati prijedlog rješenja ugradnje ovakvog sustava. Tema se nudi studentima stručnog studija ili preddiplomskog studija.', 'https://stup.ferit.hr/2020/01/29/3-projektiranje-sustava-dojave-pozara-zakonski-ekonomski-i-tehnicki-aspekti/', '05128411490');
INSERT INTO diplomski_radovi (id, naziv_rada, tekst_rada, link_rada, oib_tvrtke)
VALUES('28', '3.	Projektiranje sustava dojave požara &#8211; zakonski, ekonomski i tehnički aspekti', 'Zadatak rada je analizirati važnost sustava dojave požara, zakonsku regulativu, ekonomski aspekt ugradnje sustava te na primjeru iz prakse dati prijedlog rješenja ugradnje ovakvog sustava. Tema se nudi studentima stručnog studija ili preddiplomskog studija.', 'https://stup.ferit.hr/2020/01/29/3-projektiranje-sustava-dojave-pozara-zakonski-ekonomski-i-tehnicki-aspekti/', '05128411490');
INSERT INTO diplomski_radovi (id, naziv_rada, tekst_rada, link_rada, oib_tvrtke)
VALUES('29', 'Tema za završni i diplomski rad &#8211; Platforma za poticanje kuhanja zdrave hrane', '', 'https://stup.ferit.hr/2021/11/19/tema-za-zavrsni-i-diplomski-rad-platforma-za-poticanje-kuhanja-zdrave-hrane/', '47726994562');
INSERT INTO diplomski_radovi (id, naziv_rada, tekst_rada, link_rada, oib_tvrtke)
VALUES('30', 'Tema za završni i diplomski rad &#8211; Platforma za poticanje kuhanja zdrave hrane', '', 'https://stup.ferit.hr/2021/11/19/tema-za-zavrsni-i-diplomski-rad-platforma-za-poticanje-kuhanja-zdrave-hrane/', '47726994562');
INSERT INTO diplomski_radovi (id, naziv_rada, tekst_rada, link_rada, oib_tvrtke)
VALUES('31', 'Tema za završni i diplomski rad &#8211; Platforma za poticanje kuhanja zdrave hrane', '', 'https://stup.ferit.hr/2021/11/19/tema-za-zavrsni-i-diplomski-rad-platforma-za-poticanje-kuhanja-zdrave-hrane/', '47726994562');
INSERT INTO diplomski_radovi (id, naziv_rada, tekst_rada, link_rada, oib_tvrtke)
VALUES('32', 'Teme za diplomske radove 3.dio', 'ZADATAK: Istražiti SoC algoritme u literaturi s naglaskom na Kalman filtriranje. Odabrani algoritam implementirati na Xilinx FPGA razvojnom sustavu i Vivado programskoj podršci te mjeriti vremena izvođenja.', 'https://stup.ferit.hr/2019/01/28/teme-za-diplomske-radove-3-dio/', '70036017051');
INSERT INTO diplomski_radovi (id, naziv_rada, tekst_rada, link_rada, oib_tvrtke)
VALUES('33', '3.	Projektiranje sustava dojave požara &#8211; zakonski, ekonomski i tehnički aspekti', 'Zadatak rada je analizirati važnost sustava dojave požara, zakonsku regulativu, ekonomski aspekt ugradnje sustava te na primjeru iz prakse dati prijedlog rješenja ugradnje ovakvog sustava. Tema se nudi studentima stručnog studija ili preddiplomskog studija.', 'https://stup.ferit.hr/2020/01/29/3-projektiranje-sustava-dojave-pozara-zakonski-ekonomski-i-tehnicki-aspekti/', '05128411490');
INSERT INTO diplomski_radovi (id, naziv_rada, tekst_rada, link_rada, oib_tvrtke)
VALUES('34', 'Implementiranje mobilnog marketinga u promocijski miks integrirane marketinške komunikacije putem android aplikacije namijenjene posjetiteljima Nacionalnog parka Paklenica (diplomski studij)', 'Zadatak rada: Definirati osnovne pojmove i teorijske pretpostavke mobilnog marketinga kao sastavnog dijela integrirane marketinške komunikacije,  te izraditi android aplikaciju kao primjer implementiranja modernih tehnologija u turizmu, a u svrhu individualiziranih marketinških komunikacija.', 'https://stup.ferit.hr/2018/01/29/implementiranje-mobilnog-marketinga-u-promocijski-miks-integrirane-marketinske-komunikacije-putem-android-aplikacije-namijenjene-posjetiteljima-nacionalnog-parka-paklenica-diplomski-studij/', '9549425995201');
INSERT INTO diplomski_radovi (id, naziv_rada, tekst_rada, link_rada, oib_tvrtke)
VALUES('35', 'Sustav za upravljanje visinom i silom napetosti trake između dva valjačka stana u toplom valjanju. (Looper-tension control system in hot rolling mills)-Diplomski rad', 'Ako imate volju i želju za novim cutting edge tehnologojima, ako vas veseli svaki uspjeh a problem shvaćate kao izazov dođite. Diplomske radove smo prepoznali kao najefikasniji način odabira novih zaposlenika te stoga svim zainteresiranima pokušavamo dati priliku.', 'https://stup.ferit.hr/2018/01/20/sustav-za-upravljanje-visinom-i-silom-napetosti-trake-izmedu-dva-valjacka-stana-u-toplom-valjanju-looper-tension-control-system-in-hot-rolling-mills/', '88285726558');
INSERT INTO diplomski_radovi (id, naziv_rada, tekst_rada, link_rada, oib_tvrtke)
VALUES('36', 'Ponuda završnih i diplomskih radova iz područja automatike', 'Kao i prošlih godina, tvrtka TEO-Belišće d.o.o. nudi zainteresiranim studentima su-mentoriranje završnih i diplomskih radova iz područja automatike (industrijski procesi, automatizacija postrojenja, upravljanje strojevima, PLC i HMI/SCADA aplikacije, fieldbus komunikacija i sl.) i projektiranja za industriju (EPLAN, konstruiranje upravljačkih ormara i sl).', 'https://stup.ferit.hr/2018/12/03/ponuda-zavrsnih-i-diplomskih-radova-iz-podrucja-automatike-2/', '40480660548');
